version: '3.5'
services:
  spark:
    build: spark/.
    ports:
      - "8888:8888"
      - "4040-4049:4040-4049"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network