apiVersion: v1
kind: Secret
metadata:
  name: nessie-postgres-creds
type: Opaque
stringData:
  username: null # <----
  password: null # <----
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  access_key_id: null # <----
  secret_access_key: null # <----