apiVersion: v1
kind: Secret
metadata:  
  name: nessie-postgres-creds
type: Opaque
data:
  username: null # <----
  password: null # <----
---
apiVersion: v1
kind: Secret
metadata:  
  name: s3-creds
type: Opaque
data:
  access_key: null # <----
  secret_key: null # <----