# PVC Yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-master-pvc
  labels:
    app: spark-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
