apiVersion: v2
name: datalake
description: A Helm chart for a data lake on Kubernetes (spark, dremio, iceberg, minio)

type: application

version: 0.1.0

dependencies:
- name: nessie
  version: 0.73.0
  repository: https://charts.projectnessie.org
- name: airflow
  version: 1.11.0
  repository: https://airflow.apache.org
- name: dremio
  version: 2.0.0
  repository: "file://../dremio-cloud-tools/charts/dremio_v2"

